languages = \
{
	"english": {
		"self": "english",
		"": "",
		"Last Name": "Last Name: ",
		"First Name": "First Name: ",
		"Chinese Name": "Chinese Name: ",
		"School Location": "School Location: ",
		"Barcode": "Barcode: ",
		"Old Student ID": "Old Student ID: ",
		"Date of Birth": "Date of Birth: ",
		"Age": "Age: ",
		"Gender": "Gender: ",
		"Parent Name": "Parent Name: ",
		"Home Phone": "Home Phone: ",
		"Cell Phone": "Cell Phone: ",
		"Cell Phone 2": "Cell Phone 2: ",
		"Pick up Person": "Pick up Person: ",
		"Address": "Address: ",
		"State": "State: ",
		"City": "City: ",
		"Zipcode": "Zipcode: ",
		"Weekday/Weekend": "Weekday/Weekend: ",
		"Tuition Paid Day": "Tuition Paid Day: ",
		"Payment Method": "Payment Method: ",
		"Tuition Pay Amount": "Payment Amount: ",
		"E-mail": "E-mail: ",
		"Service Type": "Service Type: ",
		"Classes Awarded": "Classes Awarded: ",
		"Classes Remaining": "Classes Remaining",
		"Date": "Date",
		"Check-In Time": "Check-In Time",
		"Class Time": "Class Time",
		"How did you hear about the school?": "How did you hear\nabout this school?",
		"Notes": "Notes",
		"No student": "\nStudent was not found!\nType in the correct name or \n contact your system administrator.",
		"Con student": "\nAre you sure you would like\nto add this to the Database?",
		"Ase student": "\nStudent with this barcode exists in the database\nAdding this student will overwrite the existing student\n.Overwrite current student?\n",
		"Sa student": "\nStudent has been added to the database.",
		"Cs student": "\nCheck in the student?\n",
		"ok": "    OK    ",
		"yes": "    YES    ",
		"no": "    NO    ",
		"impdb": "Import Database",
		"expdb": "Export Database",
		"impxls": "Import from Excel",
		"impt": "Import Time Data",
		"imptxls": "Import from Excel",
		"expxls": "Export to Excel",
		"curfile": "Current Database File",
		"browse": "Browse",
		"filepath": "File Path",
		"back": "Back",
		"next": "Next",
		"saveto": "Save To",
		"save": "Save",
		"choosedb": "Choose Database",
		"changelanguage": "更改语言"
		},

	"chinese": {
		"self": "chinese",
		"First Name": "名: ",
		"Last Name": "姓: ",
		"Chinese Name": "中国名字: ",
		"School Location": "学校位置: ",
		"Barcode": "条码号: ",
		"Old Student ID": "旧学号: ",
		"Date of Birth": "出生日期: ",
		"Age": "年龄: ",
		"Gender": "性别: ",
		"Parent Name": "家长姓名: ",
		"Home Phone": "家庭电话: ",
		"Cell Phone": "手机: ",
		"Cell Phone 2": "手机 2: ",
		"Pick up Person": "学生接人: ",
		"Address": "住址: ",
		"State": "州: ",
		"City": "城市: ",
		"Zipcode": "邮政编码: ",
		"Weekday/Weekend": "平日/周末: ",
		"Tuition Paid Day": "支付学费日期: ",
		"Payment Method": "付款方式: ",
		"Tuition Pay Amount": "Payment Amount: ",
		"E-mail": "电子邮件: ",
		"Service Type": "课程级别: ",
		"Classes Awarded": "加入学生课程: ",
		"Classes Remaining": "Classes Remaining",
		"Date": "日期",
		"Check-In Time": "记录时间",
		"Class Time": "课程时间段",
		"How did you hear about the school?": "你是怎么找到我们学校?",
		"Notes": "笔记",
		"No student": "\nStudent was not found!\nType in the correct name or \n contact your system administrator.",
		"Con student": "\nAre you sure you would like\nto add this to the Database?",
		"Ase student": "\nStudent with this barcode exists in the database\nAdding this student will overwrite the existing student\n.Overwrite current student?\n",
		"Sa student": "\nStudent has been added to the database.",
		"Cs student": "\n你想要记录这个学生？\n",
		"ok": "    OK    ",
		"yes": "    确认    ",
		"no": "    不记录    ",
		"changelanguage": "Change Language"
	}
		
}

#try:
#	int('s')
#except ValueError:
#	print('s is not an int')

#print([n for n in range(2, 3)])